export const jotStyles = `
.jot-app{--jot-bg:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,#fff));--jot-fg:var(--dsw-alias-label-primary,#23262b);--jot-muted:var(--dsw-alias-label-secondary,#626a75);--jot-line:var(--dsw-alias-border-l3,var(--dsw-alias-border-l2,#e1e4e9));--jot-hover:var(--dsw-alias-interactive-bg-hover,var(--dsw-alias-interactive-bg-hover-solid,#f3f4f6));--jot-accent:var(--dsw-static-blue-450,var(--dsw-alias-state-business-primary,#356cbb));--jot-secondary-font:var(--dsw-font-xs-13,inherit);--jot-caption-font:var(--dsw-font-xxs-12,inherit);box-sizing:border-box;color:var(--jot-fg);background:var(--jot-surface,var(--jot-bg));font:var(--dsw-font-s-14,inherit);font-family:var(--dsw-font-family,inherit);font-size:var(--dsh-content-font-size,14px);line-height:calc(22px + var(--dsh-content-font-delta,0px));width:100%;height:100%;min-height:0;min-width:0;display:flex;flex-direction:column;isolation:isolate;position:relative}
.jot-workbench-header{display:flex;align-items:center;gap:8px;box-sizing:border-box;width:100%;min-width:0;height:1.75rem;min-height:1.75rem;padding:0 20px;flex:none;box-shadow:inset 0 -1px 0 var(--jot-line)}
.jot-workbench-header>svg{width:16px;height:16px}.jot-workbench-header .jot-brand{margin-inline-end:4px;font-size:13px;font-weight:600;line-height:1}:is(.jot-workbench-header,.jot-topbar) :is(.jot-btn,.jot-icon-btn,.jot-back){height:24px;min-height:24px}:is(.jot-workbench-header,.jot-topbar) .jot-icon-btn{width:24px}
.jot-overlay-root{--jot-bg:var(--dsw-alias-bg-layer-1,var(--dsw-alias-bg-base,#fff));--jot-fg:var(--dsw-alias-label-primary,#23262b);--jot-muted:var(--dsw-alias-label-secondary,#626a75);--jot-line:var(--dsw-alias-border-l3,var(--dsw-alias-border-l2,#e1e4e9));--jot-hover:var(--dsw-alias-interactive-bg-hover,var(--dsw-alias-interactive-bg-hover-solid,#f3f4f6));--jot-accent:var(--dsw-static-blue-450,var(--dsw-alias-state-business-primary,#356cbb));--jot-secondary-font:var(--dsw-font-xs-13,inherit);--jot-caption-font:var(--dsw-font-xxs-12,inherit);color:var(--jot-fg);font:var(--dsw-font-s-14,inherit);font-family:var(--dsw-font-family,inherit);font-size:var(--dsh-content-font-size,14px);line-height:calc(22px + var(--dsh-content-font-delta,0px))}
.jot-overlay-root *{box-sizing:border-box}.jot-overlay-root button,.jot-overlay-root input,.jot-overlay-root select,.jot-overlay-root textarea{font:inherit;color:inherit}.jot-overlay-root button{cursor:pointer}.jot-overlay-root button:disabled{cursor:default;opacity:.5}.jot-overlay-root button,.jot-overlay-root input,.jot-overlay-root select{outline-offset:3px}.jot-overlay-root :focus-visible{outline:2px solid var(--jot-accent)}
html[data-platform=darwin] .jot-wide.jot-host-chrome .jot-workbench-header{padding-inline-start:max(20px,var(--dsh-frame-leading-clearance,0px));-webkit-app-region:drag}
.jot-workbench-header button,.jot-workbench-header input,.jot-workbench-header select,.jot-workbench-header a{-webkit-app-region:no-drag}
.jot-app,.jot-overlay-root{--jot-search-highlight:color-mix(in srgb,var(--jot-accent) 22%,var(--jot-bg));--jot-find-highlight:color-mix(in srgb,var(--jot-accent) 22%,var(--jot-bg));--jot-find-active:color-mix(in srgb,var(--jot-accent) 38%,var(--jot-bg))}
.jot-app *{box-sizing:border-box}.jot-app button,.jot-app input,.jot-app select,.jot-app textarea{font:inherit;color:inherit}.jot-app button{cursor:pointer}.jot-app button:disabled{cursor:default;opacity:.5}.jot-app button,.jot-app input,.jot-app select{outline-offset:3px}.jot-app :focus-visible{outline:2px solid var(--jot-accent)}

.jot-topbar{display:flex;align-items:center;gap:8px;box-sizing:border-box;height:1.75rem;min-height:1.75rem;padding:0 12px;flex:none;box-shadow:inset 0 -1px 0 var(--jot-line)}[data-tree-group][data-zone-header] .jot-topbar{box-shadow:none}
.jot-brand{font:inherit;font-size:calc(var(--dsh-content-font-size,14px) + 2px);font-weight:600;line-height:1.5;letter-spacing:0;white-space:nowrap}
.jot-toolbar-label{font:inherit;font-weight:500;line-height:22px;color:var(--jot-fg);white-space:nowrap}.jot-toolbar-end{display:inline-flex;align-items:center;gap:4px;margin-inline-start:auto;flex:none}
.jot-btn,.jot-icon-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;border:1px solid var(--jot-line);border-radius:var(--dsw-radius-sm,8px);background:transparent;height:28px;min-height:28px;line-height:1;padding:0 8px;white-space:nowrap;flex:none}
.jot-btn:hover,.jot-icon-btn:hover{background:var(--jot-hover)}.jot-btn:active,.jot-icon-btn:active,.jot-format:active{background:var(--jot-hover)}
.jot-icon-btn{width:28px;height:28px;padding:0;display:inline-flex;align-items:center;justify-content:center;border-color:transparent;border-radius:6px;color:var(--jot-muted)!important}.jot-icon-btn[aria-pressed=true],.jot-icon-btn[aria-expanded=true]{background:var(--jot-hover);color:var(--jot-fg)!important}.jot-action-icon{display:block;width:16px;height:16px;flex:none}
:is(.jot-app,.jot-overlay-root) .jot-btn.jot-primary{border-color:transparent;background:var(--dsw-alias-button-primary-fill,var(--jot-accent));color:var(--dsw-alias-label-primary-inverted,#fff)!important;font-weight:500}:is(.jot-app,.jot-overlay-root) .jot-btn.jot-primary:hover:not(:disabled){background:var(--dsw-alias-button-primary-hover,var(--jot-accent))}
:is(.jot-app,.jot-overlay-root) .jot-btn.jot-danger-fill{border-color:transparent;background:var(--jot-danger-fill,var(--dsw-alias-state-error-primary,#c2410c));color:var(--jot-danger-ink,#fff)!important;font-weight:500}:is(.jot-app,.jot-overlay-root) .jot-btn.jot-danger-fill:hover:not(:disabled){filter:brightness(.94)}
.jot-new-note-btn{gap:4px;padding:0;padding-inline:7px 10px;font:var(--jot-secondary-font);line-height:1}
.jot-text-btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;border:0;background:transparent;height:28px;min-height:28px;padding:0 6px;color:var(--jot-accent)!important;font:var(--jot-secondary-font);line-height:1;white-space:nowrap}.jot-text-btn:hover{text-decoration:underline}.jot-danger{color:var(--dsw-alias-state-error-primary,#b44c4c)!important}

.jot-search{position:relative;display:flex;align-items:center;min-width:0;flex:none}.jot-search input{width:100%;min-height:28px;padding:3px 0;padding-inline:32px 28px;border:1px solid var(--jot-line);border-radius:var(--dsw-radius-sm,8px);background:transparent;font:inherit;line-height:20px}.jot-search input::placeholder,.jot-folder-form input::placeholder{color:var(--jot-muted);opacity:1}.jot-search>.jot-action-icon{position:absolute;inset-inline-start:10px;top:50%;transform:translateY(-50%);color:var(--jot-muted);pointer-events:none}.jot-search input::-webkit-search-cancel-button{-webkit-appearance:none;appearance:none;display:none}.jot-search-clear{position:absolute;inset-inline-end:4px;top:50%;transform:translateY(-50%);display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;padding:0;border:0;border-radius:5px;background:transparent;color:var(--jot-muted)!important}.jot-search-clear:hover{background:var(--jot-hover);color:var(--jot-fg)!important}
.jot-layout{display:flex;flex:1;min-height:0;min-width:0;overflow:hidden}.jot-list-panel{width:280px;max-width:45%;flex:none;display:flex;flex-direction:column;min-height:0;min-width:0;border-inline-end:1px solid var(--jot-line);container:jot-list / inline-size}
.jot-list-controls{padding:8px 12px 4px;display:flex;flex-direction:column;gap:6px;flex:none}.jot-folder-line{display:flex;align-items:center;gap:4px;min-width:0}.jot-folder-placeholder{flex:1;min-width:0;color:var(--jot-muted);font:var(--jot-secondary-font)}.jot-select{appearance:auto;min-width:0;flex:1;width:100%;min-height:28px;border:1px solid var(--jot-line);border-radius:6px;background:transparent;padding:3px 6px;font:var(--jot-secondary-font);line-height:20px}.jot-select option{background-color:var(--jot-bg);color:var(--jot-fg)}
.jot-browse-line{display:flex;align-items:center;gap:8px;min-width:0}.jot-view-line{display:flex;align-items:center;gap:12px;flex:1;min-width:0}.jot-view-line button{border:0;background:transparent;font:var(--jot-secondary-font);line-height:20px;min-height:28px;padding:2px 0;color:var(--jot-muted);white-space:nowrap}.jot-view-line button[aria-pressed=true]{color:var(--jot-fg);font-weight:600}.jot-list-total{color:var(--jot-muted);font:var(--jot-caption-font);font-variant-numeric:tabular-nums;padding:0 2px}.jot-list-label.jot-search-label{padding:2px 14px 4px;justify-content:flex-start}
.jot-note-list{overflow-y:auto;overflow-x:hidden;overscroll-behavior:contain;flex:1;padding:0 6px 10px;min-height:0}.jot-list-label{padding:6px 8px 4px;color:var(--jot-muted);font:var(--jot-caption-font);display:flex;align-items:center;justify-content:space-between;gap:8px}.jot-list-label>span:last-child,.jot-selection-bar>span,.jot-find-count{font-variant-numeric:tabular-nums}
.jot-note-row{display:block;width:100%;text-align:start;border:1px solid transparent;border-radius:var(--dsw-radius-sm,8px);background:transparent;padding:7px 8px;margin-bottom:2px}.jot-note-row:hover{background:var(--jot-hover)}.jot-note-row[aria-current=true]{background:var(--jot-hover);border-color:var(--jot-line)}
.jot-note-title{display:flex;align-items:center;gap:6px;font:inherit;font-weight:600;line-height:22px;overflow:hidden}.jot-note-title span:first-child{white-space:nowrap;text-overflow:ellipsis;overflow:hidden}.jot-note-pin{color:var(--jot-muted);flex:none;font:var(--jot-caption-font)}.jot-note-title.is-untitled{color:var(--jot-muted);font-weight:500}
.jot-note-excerpt{font:var(--jot-secondary-font);color:var(--jot-muted);overflow:hidden;text-overflow:ellipsis;white-space:normal;margin:2px 0 4px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical}.jot-compact .jot-note-excerpt{-webkit-line-clamp:1!important}.jot-compact .jot-search-results .jot-note-excerpt{-webkit-line-clamp:2!important}.jot-note-meta{display:flex;gap:10px;align-items:center;min-width:0;color:var(--jot-muted);font:var(--jot-caption-font)}.jot-note-progress,.jot-note-agent,.jot-agent-chip{display:inline-flex;align-items:center;gap:3px;flex:none;white-space:nowrap;font-variant-numeric:tabular-nums}.jot-note-agent,.jot-agent-chip{color:var(--dsw-alias-state-business-primary,var(--jot-accent))}.jot-note-folder{margin-inline-start:auto}
.jot-empty{padding:28px 18px;text-align:center;color:var(--jot-muted);font:var(--jot-secondary-font)}.jot-empty p{margin:6px 0 14px}.jot-empty-title{color:var(--jot-fg);font:var(--dsw-font-s-strong-14,inherit);font-weight:600}
.jot-agent-line{box-sizing:border-box;height:28px;min-height:28px;padding:0 12px;flex:none;display:flex;align-items:center;justify-content:space-between;gap:8px;font:var(--jot-secondary-font);color:var(--jot-muted)}.jot-agent-label{display:block;min-width:0;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.jot-agent-label>svg{display:inline-block!important;vertical-align:top;margin-block-start:calc(.5lh - 7px);margin-inline-end:6px}
.jot-switch{border:0;width:30px;height:17px;border-radius:20px;background:var(--jot-line);position:relative;flex:none}.jot-switch:after{content:'';width:13px;height:13px;inset-inline-start:2px;top:2px;border-radius:50%;position:absolute;background:#fff;box-shadow:0 1px 2px #0002}.jot-switch[aria-checked=true]{background:var(--jot-accent)}.jot-switch[aria-checked=true]:after{inset-inline-start:15px}

.jot-editor-panel{flex:1;min-width:0;min-height:0;display:flex;flex-direction:column;overflow:hidden;container:jot-editor / inline-size}.jot-context-toolbar{display:flex;align-items:center;gap:6px;height:38px;min-height:38px;padding:0;padding-inline:16px 6px;flex:none;min-width:0;font:var(--jot-secondary-font);color:var(--jot-muted)}.jot-context-toolbar .jot-select{width:auto;flex:0 1 160px;max-width:35%;border-color:transparent;padding-inline-start:0}.jot-save-slot{margin-inline-start:auto;display:inline-flex;align-items:center;min-width:0;flex:0 1 auto}.jot-save-label{display:inline-block;white-space:nowrap;min-width:3.5ch;max-width:16ch;overflow:hidden;text-overflow:ellipsis;padding:0 4px}.jot-save-label.is-action{height:24px;border:0;border-radius:5px;background:transparent;color:var(--jot-fg)!important;font:inherit;cursor:pointer}.jot-save-label.is-action:hover{background:var(--jot-hover)}.jot-save-label.is-error{color:var(--dsw-alias-state-error-primary,#b44c4c)!important}.jot-agent-chip{margin-inline-start:6px;font:var(--jot-caption-font)}
.jot-document-actions{display:inline-flex;align-items:center;gap:4px;flex:none}.jot-document-actions .jot-icon-btn[aria-pressed=true]{color:var(--jot-accent)!important}
.jot-editor-body{--jot-body-pad:16px;--jot-table-gutter:min(20px,var(--jot-body-pad));flex:1;min-height:0;overflow:auto;overscroll-behavior:contain;padding:0 var(--jot-body-pad) 28px}.jot-wide .jot-editor-body{--jot-body-pad:32px}.jot-wide .jot-document{max-width:800px;margin-inline:0}.jot-title-input{display:block;resize:none;width:100%;border:0;background:transparent;padding:8px 0 10px;font:inherit!important;font-size:calc(var(--dsh-content-font-size,14px) + 2px)!important;font-weight:600!important;line-height:1.5!important;letter-spacing:0}.jot-title-input::placeholder{color:var(--jot-muted);opacity:1}.jot-title-input:focus{outline:0}
.jot-rich-editor{min-height:260px}.jot-format-bar{display:flex;align-items:center;gap:4px;padding:4px 0 8px;flex-wrap:wrap;border-bottom:1px solid var(--jot-line);margin-bottom:12px}.jot-format{display:inline-flex;align-items:center;justify-content:center;gap:6px;background:transparent;border:0;border-radius:6px;min-width:28px;height:28px;line-height:1;padding:0 6px;color:var(--jot-muted)!important;font:inherit;flex:none}.jot-format:hover,.jot-format[aria-pressed=true]{background:var(--jot-hover);color:var(--jot-fg)!important}.jot-format-bold{font-weight:700!important}.jot-format-italic{font-style:italic!important}
.jot-editor-mount .ProseMirror{outline:none;min-height:220px;font:var(--dsw-font-markdown-base,inherit);font-size:var(--dsh-content-font-size,inherit);line-height:calc(24px + var(--dsh-content-font-delta,0px));overflow-wrap:anywhere}.jot-editor-mount .ProseMirror:focus-visible{outline:0}.jot-editor-mount .ProseMirror p{margin:0 0 10px}
.jot-editor-mount .ProseMirror h1{font-size:calc(var(--dsh-content-font-size,14px) + 2px)}.jot-editor-mount .ProseMirror h2{font-size:calc(var(--dsh-content-font-size,14px) + 1px)}.jot-editor-mount .ProseMirror h3,.jot-editor-mount .ProseMirror h4,.jot-editor-mount .ProseMirror h5,.jot-editor-mount .ProseMirror h6{font-size:inherit}.jot-editor-mount .ProseMirror h1,.jot-editor-mount .ProseMirror h2,.jot-editor-mount .ProseMirror h3,.jot-editor-mount .ProseMirror h4,.jot-editor-mount .ProseMirror h5,.jot-editor-mount .ProseMirror h6{font-weight:600;line-height:1.5;margin:18px 0 8px;letter-spacing:0}.jot-editor-mount .ProseMirror h3{font-weight:550}
/* Notes keep the direction of their own text in either interface direction (Arabic UI, Chinese note). */
.jot-editor-mount .ProseMirror :is(p,h1,h2,h3,h4,h5,h6,pre),.jot-note-title span:first-child,.jot-note-excerpt{unicode-bidi:plaintext;text-align:start}
.jot-editor-mount .ProseMirror a{color:var(--dsw-alias-link,var(--jot-accent));text-decoration:underline;text-decoration-thickness:1px;text-underline-offset:2px;cursor:pointer}
.jot-editor-mount .ProseMirror blockquote{margin:8px 0 12px;padding:2px 0;padding-inline-start:12px;border-inline-start:3px solid var(--dsw-alias-border-l2,var(--jot-line));color:var(--jot-muted)}.jot-editor-mount .ProseMirror blockquote>:last-child{margin-bottom:0}
.jot-editor-mount .ProseMirror code{font-family:var(--dsw-font-family-mono,ui-monospace,SFMono-Regular,Menlo,Consolas,monospace);font-size:.9em;padding:1px 4px;border-radius:4px;background:var(--dsw-alias-markdown-inline-code,var(--jot-hover))}
.jot-editor-mount .ProseMirror pre{margin:8px 0 12px;padding:10px 12px;border-radius:6px;background:var(--dsw-alias-markdown-code-block,var(--jot-hover));overflow-x:auto;line-height:1.6;white-space:pre}.jot-editor-mount .ProseMirror pre code{padding:0;background:transparent;font-size:.88em}
.jot-editor-mount .ProseMirror hr{border:0;border-top:1px solid var(--jot-line);margin:16px 0}.jot-editor-mount .ProseMirror hr.ProseMirror-selectednode{border-top-color:var(--jot-accent)}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror [data-jot-color="#374151"],body[data-ds-dark-theme] .jot-color-swatch[data-color="#374151"]{color:var(--jot-muted)!important}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror [data-jot-color="#dc2626"],body[data-ds-dark-theme] .jot-color-swatch[data-color="#dc2626"]{color:#f87171!important}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror [data-jot-color="#d97706"],body[data-ds-dark-theme] .jot-color-swatch[data-color="#d97706"]{color:#fbbf24!important}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror [data-jot-color="#16a34a"],body[data-ds-dark-theme] .jot-color-swatch[data-color="#16a34a"]{color:#4ade80!important}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror [data-jot-color="#2563eb"],body[data-ds-dark-theme] .jot-color-swatch[data-color="#2563eb"]{color:#60a5fa!important}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror [data-jot-color="#9333ea"],body[data-ds-dark-theme] .jot-color-swatch[data-color="#9333ea"]{color:#c084fc!important}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror [data-jot-color="#db2777"],body[data-ds-dark-theme] .jot-color-swatch[data-color="#db2777"]{color:#f472b6!important}
body[data-ds-dark-theme] .jot-editor-mount .ProseMirror mark[data-color]{color:inherit!important}
body[data-ds-dark-theme] :is(.jot-editor-mount .ProseMirror mark,.jot-highlight-swatch)[data-color="#fef08a"]{background-color:rgba(234,179,8,.34)!important}
body[data-ds-dark-theme] :is(.jot-editor-mount .ProseMirror mark,.jot-highlight-swatch)[data-color="#fed7aa"]{background-color:rgba(249,115,22,.34)!important}
body[data-ds-dark-theme] :is(.jot-editor-mount .ProseMirror mark,.jot-highlight-swatch)[data-color="#bbf7d0"]{background-color:rgba(34,197,94,.30)!important}
body[data-ds-dark-theme] :is(.jot-editor-mount .ProseMirror mark,.jot-highlight-swatch)[data-color="#bfdbfe"]{background-color:rgba(59,130,246,.36)!important}
body[data-ds-dark-theme] :is(.jot-editor-mount .ProseMirror mark,.jot-highlight-swatch)[data-color="#e9d5ff"]{background-color:rgba(168,85,247,.36)!important}
body[data-ds-dark-theme] :is(.jot-editor-mount .ProseMirror mark,.jot-highlight-swatch)[data-color="#fecdd3"]{background-color:rgba(244,63,94,.32)!important}
.jot-editor-mount .ProseMirror ul,.jot-editor-mount .ProseMirror ol{padding-inline-start:22px;margin:8px 0 12px}.jot-editor-mount .ProseMirror li p{margin-bottom:3px}.jot-editor-mount .ProseMirror ul[data-type=taskList]{list-style:none;padding:0}.jot-editor-mount .ProseMirror ul[data-type=taskList] li{display:flex;gap:8px;align-items:flex-start;margin:5px 0}.jot-editor-mount .ProseMirror ul[data-type=taskList] li>label{padding-top:3px;flex:none;user-select:none}.jot-editor-mount .ProseMirror ul[data-type=taskList] li>div{flex:1;min-width:0}.jot-editor-mount .ProseMirror input[type=checkbox]{accent-color:var(--jot-accent);cursor:pointer}.jot-editor-mount .ProseMirror li[data-checked=true]>div>p{color:var(--jot-muted);text-decoration:line-through}.jot-editor-mount .ProseMirror[data-empty=true]:has(>p:first-child):before{content:attr(data-placeholder);float:inline-start;height:0;pointer-events:none;color:var(--jot-muted)}

.jot-notice{margin:0 12px 8px;padding:8px 10px;border:1px solid var(--jot-line);border-radius:7px;background:var(--jot-hover);font:var(--jot-secondary-font);flex:none}.jot-notice p{margin:0 0 5px}.jot-notice.is-error{border-color:color-mix(in srgb,var(--dsw-alias-state-error-primary,#b44c4c) 40%,var(--jot-line))}.jot-notice-actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.jot-global-error{display:flex;align-items:center;gap:8px;margin:8px 12px;padding:6px;padding-inline-start:10px;border-radius:7px;background:color-mix(in srgb,var(--dsw-alias-state-error-primary,#b44c4c) 10%,var(--jot-bg));color:var(--dsw-alias-state-error-primary,#b44c4c);font:var(--jot-secondary-font)}.jot-global-error>span{flex:1;min-width:0;overflow-wrap:anywhere;white-space:pre-line;max-height:9.5em;overflow-y:auto}
.jot-inline-confirm{padding:8px 10px;border:1px solid var(--jot-line);border-radius:7px;background:var(--jot-hover);font:var(--jot-secondary-font)}.jot-inline-confirm p{margin:0 0 8px}.jot-inline-confirm .jot-notice-actions{justify-content:flex-end;gap:8px}
.jot-toast{position:absolute;left:50%;bottom:56px;transform:translateX(-50%);z-index:30;display:flex;align-items:center;gap:6px;width:max-content;max-width:calc(100% - 24px);padding:5px;padding-inline-start:12px;border-radius:8px;background:var(--dsw-alias-toast-bg,#2b2f36);color:var(--jot-toast-fg,#fff);font:var(--jot-secondary-font);box-shadow:0 6px 20px #0003}.jot-toast>span{min-width:0;overflow-wrap:anywhere}.jot-toast .jot-text-btn{color:var(--jot-toast-fg,#fff)!important;font-weight:600;padding:0 8px;border-radius:5px}.jot-toast .jot-text-btn:hover{background:var(--jot-toast-hover,#ffffff1f);text-decoration:none}.jot-toast-close{display:inline-flex;align-items:center;justify-content:center;width:24px;height:24px;flex:none;padding:0;border:0;border-radius:5px;background:transparent;color:var(--jot-toast-muted,#ffffffb3)!important}.jot-toast-close:hover{background:var(--jot-toast-hover,#ffffff1f);color:var(--jot-toast-fg,#fff)!important}
.jot-resize-handle{position:relative;z-index:3;flex:none;width:7px;margin:0;margin-inline:-3px -4px;cursor:col-resize;touch-action:none;outline:none}.jot-resize-handle:after{content:'';position:absolute;top:0;bottom:0;inset-inline-start:3px;width:1px;background:transparent;transition:background .12s ease}.jot-resize-handle:hover:after,.jot-resize-handle:focus-visible:after{background:var(--jot-accent);width:2px;inset-inline-start:2px}
.jot-editor-empty{margin:auto;display:flex;flex-direction:column;align-items:center;gap:2px}.jot-editor-empty .jot-btn{margin-top:4px}.jot-attachment-error{color:var(--dsw-alias-state-error-primary,#b44c4c)!important}.jot-loading{display:flex;align-items:center;justify-content:center;flex:1;min-height:160px;color:var(--jot-muted);font:inherit}
.jot-folder-form{display:flex;gap:6px;margin-top:2px}.jot-folder-form input{width:100%;min-width:0;min-height:28px;border:1px solid var(--jot-line);border-radius:6px;padding:3px 6px;font:inherit;background:transparent}.jot-folder-form .jot-btn{font:var(--jot-secondary-font);padding:3px 7px;min-height:28px}
.jot-compact .jot-topbar{padding:0;padding-inline:8px 6px;gap:8px}.jot-compact .jot-list-panel{width:100%;max-width:none;border:0}.jot-compact .jot-list-controls{padding:8px 10px 4px}.jot-compact .jot-note-list{padding-inline:4px}.jot-compact .jot-agent-line{padding:0 10px}.jot-compact .jot-editor-body{--jot-body-pad:14px;padding:0 var(--jot-body-pad) 24px}.jot-compact .jot-context-toolbar{padding-inline:8px 6px}.jot-compact .jot-notice{margin:0 10px 8px}.jot-back{display:inline-flex;align-items:center;justify-content:center;gap:6px;border:0;background:transparent;color:var(--jot-fg)!important;font:inherit;height:28px;min-height:28px;line-height:1;padding:0;white-space:nowrap;flex:none}[dir=rtl] .jot-back .jot-action-icon,.jot-back .jot-action-icon:dir(rtl){transform:scaleX(-1)}
.jot-note-meta time{flex:none;white-space:nowrap}.jot-note-folder{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.jot-compact .jot-document-find-row .jot-find-query{flex-basis:100%!important}
.jot-format-bar{position:relative}.jot-format-divider{width:1px;height:16px;margin:0 4px;background:var(--jot-line);flex:none}.jot-format-underline{text-decoration:underline;text-underline-offset:2px}.jot-format-bar .jot-format-bold,.jot-format-bar .jot-format-italic,.jot-format-bar .jot-format-underline{font-family:var(--dsw-font-family,inherit)}
.jot-format-popover{position:absolute;top:calc(100% - 4px);inset-inline-start:0;z-index:15;display:flex;flex-direction:column;gap:0;width:max-content;min-width:240px;max-width:min(380px,100%);padding:4px;border:1px solid var(--jot-line);border-radius:8px;background:var(--jot-bg);color:var(--jot-fg);box-shadow:0 6px 20px #0000002e}.jot-format-section{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:2px;padding:4px 0}.jot-format-section+.jot-format-section{border-top:1px solid var(--jot-line)}.jot-format-popover .jot-format{justify-content:flex-start;width:100%;gap:8px;height:30px;padding:0 8px;color:var(--jot-fg)!important;font:var(--jot-secondary-font);line-height:1;white-space:nowrap}.jot-format-popover .jot-format>span:last-child{overflow:hidden;text-overflow:ellipsis}.jot-format-glyph{display:inline-flex;align-items:center;justify-content:center;min-width:22px;color:var(--jot-muted);font-weight:600;font-size:12px}.jot-format-strike .jot-format-glyph{text-decoration:line-through}.jot-format-code .jot-format-glyph,.jot-format-codeBlock .jot-format-glyph{font-family:var(--dsw-font-family-mono,ui-monospace,Menlo,monospace)}.jot-format-color-glyph{color:#dc2626}.jot-format-highlight-glyph{min-width:18px;height:18px;border-radius:3px;background:#fef08a;color:#23262b}.jot-format-popover .jot-color-palette{border-top:1px solid var(--jot-line);padding:8px 6px 4px}
body[data-ds-dark-theme] .jot-highlight-swatch{color:var(--jot-fg)!important}body[data-ds-dark-theme] .jot-format-color-glyph{color:#f87171}body[data-ds-dark-theme] .jot-format-highlight-glyph{background:rgba(234,179,8,.34);color:var(--jot-fg)}
.jot-document-find{min-width:0;font:var(--jot-secondary-font)}.jot-document-find-row,.jot-document-replace-row{min-width:0;max-width:100%;gap:8px!important}.jot-document-find input{max-width:100%;height:28px;padding:3px 7px;border:1px solid var(--jot-line);border-radius:6px;background:transparent;color:var(--jot-fg);font:inherit;line-height:20px}.jot-document-find input::placeholder{color:var(--jot-muted);opacity:1}.jot-document-find .jot-text-btn{display:inline-flex;align-items:center;justify-content:center;min-width:28px;height:28px;min-height:28px;padding:0 6px;border-radius:6px;font:inherit;line-height:1;white-space:nowrap;flex-shrink:0}.jot-document-find .jot-text-btn:hover{background:var(--jot-hover);text-decoration:none}.jot-find-count{font:var(--jot-caption-font);color:var(--jot-muted);white-space:nowrap}.jot-document-find-hit{box-decoration-break:clone;-webkit-box-decoration-break:clone}
.jot-editor-control{display:inline-flex;align-items:center;justify-content:center;gap:6px;box-sizing:border-box;height:28px;min-height:28px;line-height:1;padding:0 6px;white-space:nowrap;flex:none}.jot-editor-control-icon-only{width:28px;min-width:28px;padding:0!important}.jot-editor-control-icon{display:block;width:16px;height:16px;flex:none}.jot-editor-control-label{display:block;line-height:1;white-space:nowrap}
@container jot-editor (max-width:440px){.jot-find-open .jot-editor-control-label,.jot-table-insert .jot-editor-control-label{display:none}.jot-find-open,.jot-table-insert{width:28px;min-width:28px;padding:0}}
@container jot-editor (max-width:360px){.jot-find-open .jot-editor-control-label,.jot-table-insert .jot-editor-control-label,.jot-format-menu .jot-editor-control-label,.jot-format-menu .jot-editor-control-icon--chevron{display:none}.jot-find-open,.jot-table-insert,.jot-format-menu{width:28px;min-width:28px;padding:0}.jot-context-toolbar .jot-select{max-width:32%}.jot-document-find-row .jot-find-query{flex-basis:100%!important}}
@container jot-list (max-width:260px){.jot-browse-line,.jot-view-line{gap:8px}}
/* Long view names (Zuletzt verwendet, Корзина…) push the count and sort button to a second row instead of overlapping them. */
.jot-browse-line{flex-wrap:wrap;row-gap:0}.jot-view-line{flex:1 0 auto;min-width:max-content}.jot-view-line>button{flex:none}.jot-list-total{margin-inline-start:auto}
@media(max-width:560px){.jot-wide .jot-list-panel{width:215px;max-width:42%}.jot-wide .jot-editor-body{--jot-body-pad:16px}.jot-wide .jot-context-toolbar{padding-inline:12px 6px}}
@media(prefers-reduced-motion:no-preference){.jot-switch:after{transition:inset-inline-start .12s ease}.jot-note-row{transition:background .1s ease}}

.jot-editor-mount .ProseMirror .tableWrapper{max-width:100%;margin:12px 0}.jot-editor-mount .ProseMirror .jot-table-shell{--jot-table-overhang:min(var(--jot-table-gutter),var(--jot-body-pad,16px));position:relative;max-width:none;padding:var(--jot-table-gutter);margin:4px calc(-1 * var(--jot-table-overhang));overflow:visible}.jot-editor-mount .ProseMirror .jot-table-viewport{max-width:100%;overflow-x:auto;overscroll-behavior-inline:contain}.jot-editor-mount .ProseMirror table{border-collapse:collapse;width:100%;min-width:0;table-layout:fixed;margin:0}.jot-editor-mount .ProseMirror td,.jot-editor-mount .ProseMirror th{position:relative;min-width:88px;border:1px solid var(--jot-line);padding:6px 8px;vertical-align:top;text-align:start;overflow-wrap:anywhere}.jot-editor-mount .ProseMirror th{background:var(--jot-hover);font-weight:600}.jot-editor-mount .ProseMirror td>p:last-child,.jot-editor-mount .ProseMirror th>p:last-child{margin-bottom:0}.jot-editor-mount .ProseMirror .selectedCell:after{content:'';position:absolute;inset:0;background:var(--jot-search-highlight);pointer-events:none}.jot-editor-mount .ProseMirror .column-resize-handle{position:absolute;right:-3px;top:0;bottom:0;width:6px;background:var(--jot-accent);pointer-events:none;z-index:2}.jot-editor-mount .ProseMirror.resize-cursor,.jot-editor-mount .ProseMirror.resize-cursor *{cursor:col-resize!important}.jot-editor-mount .ProseMirror mark[data-color]{color:#23262b!important;border-radius:2px;padding:0 1px;box-decoration-break:clone;-webkit-box-decoration-break:clone}
.jot-table-chrome-mount{position:absolute;inset:0;pointer-events:none;user-select:none}.jot-table-chrome{position:absolute;inset:0;font:var(--jot-secondary-font);color:var(--jot-muted)}.jot-table-chrome button,.jot-table-chrome .jot-menu-anchor{pointer-events:auto}.jot-table-column-menu,.jot-table-row-menu,.jot-table-options{position:absolute;display:flex;width:28px;height:28px}.jot-table-column-menu{top:0;height:var(--jot-table-gutter)}.jot-table-row-menu{left:0;width:var(--jot-table-gutter)}.jot-table-options{top:0;right:0;width:var(--jot-table-gutter);height:var(--jot-table-gutter)}.jot-table-chrome .jot-menu-anchor,.jot-table-chrome .jot-menu-anchor>.jot-icon-btn{width:100%;height:100%;min-height:0}.jot-table-row-menu .jot-action-icon{transform:rotate(90deg)}.jot-table-options .jot-action-icon{width:14px;height:14px}.jot-table-chrome .jot-icon-btn:hover,.jot-table-chrome .jot-icon-btn[aria-expanded=true]{color:var(--jot-accent)!important;background:var(--jot-hover)}.jot-table-append-column,.jot-table-append-row{position:absolute;min-height:0}.jot-table-append-column{right:0;width:var(--jot-table-gutter)!important}.jot-table-append-row{height:var(--jot-table-gutter)!important}.jot-table-column-indicator,.jot-table-row-indicator{position:absolute;pointer-events:none;background:var(--jot-accent);opacity:.45}.jot-table-column-indicator{top:calc(var(--jot-table-gutter) - 2px);height:2px}.jot-table-row-indicator{left:calc(var(--jot-table-gutter) - 2px);width:2px}.jot-table-notice{position:absolute;inset-inline:var(--jot-table-gutter);bottom:0;color:var(--dsw-alias-state-error-primary,#b44c4c);font:var(--jot-caption-font);line-height:20px;background:var(--jot-bg)}
.jot-app .jot-color-palette{display:flex;align-items:center;flex-wrap:wrap;gap:8px;width:100%;min-width:0;padding:6px 2px}.jot-app .jot-color-swatch{display:inline-flex;align-items:center;justify-content:center;flex:none;width:24px;height:24px;padding:0;border:1px solid var(--jot-line);border-radius:4px;background:transparent;color:var(--jot-swatch-color);font-weight:600;line-height:1}.jot-app .jot-color-swatch span{font-size:17px;line-height:1}.jot-app .jot-color-swatch[aria-pressed=true]{outline:2px solid var(--jot-accent);outline-offset:2px}.jot-app .jot-color-swatch:hover{border-color:var(--jot-fg)}
.jot-editor-mount .ProseMirror .jot-managed-image{display:block;max-width:100%;max-height:min(60vh,520px);width:auto;height:auto;object-fit:contain;margin:12px 0;border-radius:4px;cursor:zoom-in}.jot-editor-mount .ProseMirror .jot-managed-image.ProseMirror-selectednode{outline:2px solid var(--jot-accent);outline-offset:3px}.jot-editor-mount .ProseMirror .jot-attachment-card{display:flex;align-items:center;min-width:0;max-width:100%;min-height:40px;padding:8px 10px;margin:10px 0;border:1px solid var(--jot-line);border-radius:6px;background:var(--jot-bg);color:var(--jot-fg);font:var(--jot-secondary-font);text-decoration:none;overflow-wrap:anywhere;cursor:pointer}.jot-editor-mount .ProseMirror .jot-attachment-card:hover{background:var(--jot-hover)}.jot-app .jot-attachment-unavailable{color:var(--jot-muted);font:var(--jot-secondary-font)}

:is(.jot-app,.jot-overlay-root) .jot-menu-anchor{position:relative;display:inline-flex;align-items:center;flex:none}:is(.jot-app,.jot-overlay-root) .jot-menu{position:absolute;top:calc(100% + 4px);inset-inline-end:0;z-index:20;width:max-content;min-width:160px;max-width:min(260px,calc(100vw - 16px));padding:4px;border:1px solid var(--jot-line);border-radius:8px;background:var(--jot-bg);color:var(--jot-fg);font:var(--jot-secondary-font);box-shadow:0 5px 16px #0002;-webkit-app-region:no-drag}:is(.jot-app,.jot-overlay-root) .jot-menu[hidden]{display:none}:is(.jot-app,.jot-overlay-root) .jot-menu :is([role=menuitem],[role=menuitemradio]){display:flex;align-items:center;justify-content:flex-start;gap:8px;width:100%;min-height:28px;padding:4px 8px;border:0;border-radius:4px;background:transparent;color:inherit;font:inherit;text-align:start;white-space:normal;overflow-wrap:anywhere;text-decoration:none}:is(.jot-app,.jot-overlay-root) .jot-menu :is([role=menuitem],[role=menuitemradio]):hover,:is(.jot-app,.jot-overlay-root) .jot-menu :is([role=menuitem],[role=menuitemradio]):focus-visible{background:var(--jot-hover)}:is(.jot-app,.jot-overlay-root) .jot-menu-item-label{flex:1;min-width:0}:is(.jot-app,.jot-overlay-root) .jot-menu-item-check{margin-inline-start:auto;flex:none}:is(.jot-app,.jot-overlay-root) .jot-menu [role=separator]{height:1px;margin:4px;background:var(--jot-line)}:is(.jot-app,.jot-overlay-root) .jot-menu-heading{padding:6px 8px 2px;color:var(--jot-muted);font:var(--jot-caption-font)}:is(.jot-app,.jot-overlay-root) .jot-menu-item-icon-slot{width:16px;height:16px;flex:none}:is(.jot-app,.jot-overlay-root) .jot-menu :is([role=menuitem],[role=menuitemradio]):disabled{opacity:.45;cursor:default}
.jot-modal-backdrop{position:fixed;inset:0;z-index:50;display:flex;align-items:center;justify-content:center;box-sizing:border-box;padding:16px;background:#0004;-webkit-app-region:no-drag}.jot-modal{display:flex;flex-direction:column;box-sizing:border-box;width:min(720px,100%);max-width:100%;max-height:calc(100dvh - 32px);min-height:0;border:1px solid var(--jot-line,var(--dsw-alias-border-l3,#e1e4e9));border-radius:8px;background:var(--jot-bg,var(--dsw-alias-bg-layer-1,#fff));color:var(--jot-fg,var(--dsw-alias-label-primary,#23262b));font:var(--dsw-font-s-14,inherit);overflow:hidden;box-shadow:0 8px 28px #0003}.jot-modal-header{display:flex;align-items:center;gap:8px;flex:none;min-width:0;min-height:44px;padding:7px 12px;border-bottom:1px solid var(--jot-line)}.jot-modal-header h2,.jot-modal-header h3{margin:0;flex:1;min-width:0;font:inherit;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.jot-modal-header>.jot-icon-btn{margin-inline-start:auto}.jot-modal-body{flex:1;min-height:0;min-width:0;overflow:auto;padding:12px;overscroll-behavior:contain}.jot-modal-footer{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:8px;flex:none;padding:8px 12px;border-top:1px solid var(--jot-line)}
:is(.jot-app,.jot-overlay-root) .jot-attachment-preview{display:flex;flex-direction:column;align-items:center;gap:10px;min-width:0;width:100%}:is(.jot-app,.jot-overlay-root) .jot-attachment-preview img,:is(.jot-app,.jot-overlay-root) .jot-attachment-preview-image{display:block;width:auto;height:auto;max-width:100%;max-height:min(65dvh,640px);object-fit:contain}:is(.jot-app,.jot-overlay-root) .jot-attachment-preview iframe,:is(.jot-app,.jot-overlay-root) .jot-attachment-preview-pdf{display:block;width:100%;height:min(65dvh,640px);min-height:0;border:0;border-radius:4px;background:var(--jot-bg)}:is(.jot-app,.jot-overlay-root) .jot-attachment-preview p,:is(.jot-app,.jot-overlay-root) .jot-attachment-preview figcaption{max-width:100%;margin:0;color:var(--jot-muted);font:var(--jot-secondary-font);overflow-wrap:anywhere}
:is(.jot-app,.jot-overlay-root) .jot-upload-line{display:flex;align-items:center;flex-wrap:wrap;gap:8px;padding:6px 8px;color:var(--jot-muted);font:var(--jot-secondary-font);min-width:0;overflow-wrap:anywhere}:is(.jot-app,.jot-overlay-root) .jot-drop-hint{display:flex;align-items:center;justify-content:center;min-height:40px;padding:8px 12px;border:1px dashed var(--jot-accent);border-radius:6px;color:var(--jot-fg);background:var(--jot-search-highlight);font:var(--jot-secondary-font);text-align:center;pointer-events:none}
.jot-app .jot-selection-bar{display:flex;align-items:center;flex-wrap:wrap;gap:8px;min-height:36px;padding:4px 8px;border-bottom:1px solid var(--jot-line);font:var(--jot-secondary-font)}.jot-app input.jot-note-select{width:16px;height:16px;flex:none;margin:0;accent-color:var(--jot-accent)}.jot-app button.jot-note-select{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;flex:none;padding:0;border:0;border-radius:6px;background:transparent;color:var(--jot-fg)}.jot-app button.jot-note-select:hover{background:var(--jot-hover)}
.jot-app .jot-note-selection-row>input[type=checkbox]{width:16px;height:16px;flex:none;accent-color:var(--jot-accent)}
:is(.jot-app,.jot-overlay-root) .jot-capture-form{display:flex;flex-direction:column;gap:12px;min-width:0;width:100%;font:var(--jot-secondary-font)}:is(.jot-app,.jot-overlay-root) .jot-capture-form label{display:flex;flex-direction:column;gap:4px;min-width:0}:is(.jot-app,.jot-overlay-root) .jot-capture-form input:not([type=checkbox]):not([type=radio]):not([type=file]),:is(.jot-app,.jot-overlay-root) .jot-capture-form select{width:100%;min-width:0;height:28px;padding:3px 7px;border:1px solid var(--jot-line);border-radius:6px;background:var(--jot-bg);color:var(--jot-fg);font:inherit;line-height:20px}:is(.jot-app,.jot-overlay-root) .jot-capture-form textarea{width:100%;min-width:0;min-height:96px;padding:7px;border:1px solid var(--jot-line);border-radius:6px;background:var(--jot-bg);color:var(--jot-fg);font:inherit;resize:vertical}:is(.jot-app,.jot-overlay-root) .jot-capture-form input::placeholder,:is(.jot-app,.jot-overlay-root) .jot-capture-form textarea::placeholder{color:var(--jot-muted);opacity:1}:is(.jot-app,.jot-overlay-root) .jot-capture-form input[type=checkbox],:is(.jot-app,.jot-overlay-root) .jot-capture-form input[type=radio]{accent-color:var(--jot-accent)}
:is(.jot-app,.jot-overlay-root) .jot-capture-form label{color:var(--jot-muted)}:is(.jot-app,.jot-overlay-root) .jot-capture-field{display:flex;flex-direction:column;gap:4px;min-width:0}
:is(.jot-app,.jot-overlay-root) .jot-capture-actions,:is(.jot-app,.jot-overlay-root) .jot-dialog-actions{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:8px;margin-top:4px}
:is(.jot-app,.jot-overlay-root) .jot-capture-error,:is(.jot-app,.jot-overlay-root) .jot-dialog-error{margin:0;color:var(--dsw-alias-state-error-primary,#b44c4c);font:var(--jot-secondary-font);overflow-wrap:anywhere}
:is(.jot-app,.jot-overlay-root) .jot-dialog-text{margin:0 0 12px;font:var(--jot-secondary-font);line-height:1.6}:is(.jot-app,.jot-overlay-root) .jot-dialog-text strong{color:var(--jot-fg)}
:is(.jot-app,.jot-overlay-root) .jot-dialog-field{display:flex;flex-direction:column;gap:4px;margin-bottom:12px;color:var(--jot-muted);font:var(--jot-secondary-font)}
.jot-modal.is-small{width:min(460px,100%)}
@media(max-width:360px){.jot-modal-backdrop{padding:8px}.jot-modal{max-height:calc(100dvh - 16px)}.jot-modal-header,.jot-modal-body,.jot-modal-footer{padding-inline:8px}.jot-app .jot-color-palette{gap:8px}:is(.jot-app,.jot-overlay-root) .jot-menu{max-width:calc(100vw - 16px)}}
:is(.jot-app,.jot-overlay-root) .jot-keys{flex:none;margin-inline-start:auto;padding:0 2px;border:0;background:transparent;color:var(--jot-muted);font:var(--jot-caption-font);font-family:inherit;letter-spacing:.02em;white-space:nowrap}
.jot-format-popover .jot-format .jot-format-label{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;text-align:start}
@container jot-editor (max-width:440px){.jot-format-popover .jot-keys{display:none}}
.jot-overlay-root .jot-slash-menu{position:fixed;z-index:45;display:flex;flex-direction:column;width:248px;max-width:calc(100vw - 16px);max-height:min(400px,calc(100vh - 16px));overflow-y:auto;overscroll-behavior:contain;padding:4px;border:1px solid var(--jot-line);border-radius:8px;background:var(--jot-bg);color:var(--jot-fg);font:var(--jot-secondary-font);box-shadow:0 6px 20px #0000002e}
.jot-overlay-root .jot-slash-item{display:flex;align-items:center;gap:8px;flex:none;min-height:28px;padding:0 8px;border-radius:6px;cursor:pointer;user-select:none}
.jot-overlay-root .jot-slash-item.is-active{background:var(--jot-hover)}
.jot-overlay-root .jot-slash-label{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.jot-overlay-root .jot-slash-glyph-codeBlock{font-family:var(--dsw-font-family-mono,ui-monospace,Menlo,monospace)}
.jot-overlay-root .jot-slash-hint{flex:none;margin-top:4px;padding:6px 8px 2px;border-top:1px solid var(--jot-line);color:var(--jot-muted);font:var(--jot-caption-font);white-space:nowrap}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-help{display:flex;flex-direction:column;gap:12px;font:var(--jot-secondary-font)}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:4px 24px}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-section h3{margin:8px 0 4px;color:var(--jot-muted);font:var(--jot-caption-font);font-weight:600}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-section dl{margin:0}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-row{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:28px;border-bottom:1px solid var(--jot-line)}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-row dt{min-width:0;color:var(--jot-fg)}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-row dd{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:4px;margin:0;flex:none}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-row kbd{min-width:22px;padding:1px 6px;border:1px solid var(--jot-line);border-radius:4px;background:var(--jot-hover);color:var(--jot-fg);font:var(--jot-caption-font);font-family:inherit;text-align:center;white-space:pre}
:is(.jot-app,.jot-overlay-root) .jot-shortcut-note{margin:0;color:var(--jot-muted);line-height:1.6}
:is(.jot-app,.jot-overlay-root) .jot-export-form{display:flex;flex-direction:column;gap:12px;min-width:0;font:var(--jot-secondary-font)}
:is(.jot-app,.jot-overlay-root) .jot-export-form .jot-dialog-text{margin:0}
:is(.jot-app,.jot-overlay-root) .jot-export-choices{display:flex;flex-direction:column;gap:6px;min-width:0;margin:0;padding:0;border:0}
:is(.jot-app,.jot-overlay-root) .jot-export-choices legend{margin-bottom:4px;padding:0;color:var(--jot-muted);font:var(--jot-caption-font)}
:is(.jot-app,.jot-overlay-root) .jot-export-choice{display:flex;align-items:flex-start;gap:10px;padding:8px 10px;border:1px solid var(--jot-line);border-radius:8px;cursor:pointer}
:is(.jot-app,.jot-overlay-root) .jot-export-choice:has(input:checked){border-color:var(--jot-accent);background:color-mix(in srgb,var(--jot-accent) 7%,var(--jot-bg))}
:is(.jot-app,.jot-overlay-root) .jot-export-choice input{margin:3px 0 0;flex:none;accent-color:var(--jot-accent)}
:is(.jot-app,.jot-overlay-root) .jot-export-choice span{display:flex;flex-direction:column;gap:2px;min-width:0}
:is(.jot-app,.jot-overlay-root) .jot-export-choice strong{color:var(--jot-fg);font-weight:600}
:is(.jot-app,.jot-overlay-root) .jot-export-choice small{color:var(--jot-muted);font:var(--jot-caption-font)}
:is(.jot-app,.jot-overlay-root) .jot-export-note{margin:0;color:var(--jot-muted);font:var(--jot-caption-font);line-height:1.6}
.jot-app button.jot-agent-chip{border:0;background:transparent;color:var(--dsw-alias-state-business-primary,var(--jot-accent));font:var(--jot-caption-font);cursor:pointer;border-radius:4px;padding:2px 4px;margin-inline-start:2px}
.jot-app button.jot-agent-chip:hover{background:var(--jot-hover)}
.jot-app .jot-agent-indicator{display:inline-flex;align-items:center;flex:none;color:var(--jot-accent)}
`
